# Acknowledgement {-}

The Bulkley River and Morice River watersheds are within Wet’suwet’en and Gitxsan territory. Misiyh and Ham i yaa.

Modern civilization has much work to do to address the impacts of colonialism that have resulted in and continue to harm the Yintahk/Laxyip as well as the cultures and livelihoods that have nurtured it since time immemorial.

We gratefully acknowledge the financial support of the the Habitat Conservation Trust Fund, the Provincial Fish Passage Remediation program and the Canadian Wildlife Federation. 

Our fish passage connection to the watershed began with the trust of Craig Mount, Richard Thompson and Dave Maloney from the Fish Passage Technical Working group through a 2017 project commissioned by the Ministry of Environment and Climate Change Strategy (MoE). What a blessing. Thank you.

The Skeena Fisheries Commission honoured us by putting us in touch with its members in the fall of 2019 and hosting a forum for us to give a presentation about our project in the spring of 2020.  Thank you for having the patience to listen to our story which is based on a story you told us to begin with. Thank you Kenny Rabnett, Stu Barnes, Ryneld Starr, Allison Oliver, and the rest of the teams.

Mike Risdale, David Dewit, walter Joseph and Dallas Nikal from the Office of Wet'suwet'en (and the Witset First Nation) were incredibly generous with our team, provided a letter of support for the project, allowed us into their territory and shared some of their timeless knowledge of the Yintahk.  This continues to open our eyes to incredibly wise perspectives.  Misiyh.

The Gitskan Watershed Authority had the grace to share their past work with us and provide valuable input into our study plan. Ham i yaa Alecia Fernando and the rest of the team.

Much gratitude to Simon Norris from Hillcrest Geographics and Craig Mount from MoE for leveraging decades of hard work towards the datbase management, GIS, modeling and mapping that has been absolutely essential to this work since the beginning. 

Thank you to David Wilford, Glen Buhr, Greg Tamblyn, Robyn Vaniderstine, Jesse Fraser, Chris Schell, Kenji Miyazaki, Dean Peard, Brian Kolman, Megan Peloso, Troy Larden, Beth Eagles and Julie Sheppard from FLNRORD for your insight, advise, and assistance. Among the other things you have done for us, helping us tie our project to some of the numerous initiatives in your areas has been invaluable.

We feel privileged to benefit from a great amount of hard work and significant investments of the Canadian Wildlife Federation towards the open source tools we use and develop for the analysis of study area streams/watersheds.  We also recognize that their work to coordinate the Bulkley River Fish Passage Working Group is one more massive step towards actionable plans. Thank you Nick LaPointe, David Browne, Betty Rebellato, Nick Mazany-Wright, Sarah Sra, Sami Kurani, Nick O'Hanley and Dave Hillary.  

Thank you to Karla Graf from CN Rail and Kathryn Graham from the Ministry of Transportation and Infrastructure (MoTi) for reviewing target sites, providing insight/background for individual crossings, for providing letter of support for the project and for their continuous encouragement.  

Thank you so much to Steve Page, Darren Loverin, Ron Donnelly, Tom Bosch, Mark Dewit, Visti Mosumgaard and Miro Kosalko from the FLNRORD northern engineering and forestry team for sharing their experience, knowledge and know-how related to road engineering and what it takes to pull stream crossing replacement/removal planning off with style and good humour. 

Thank you to the crew at DFO who sluthed out reports and put us in touch with the powers and places that be. Thank you Sandra Devcic, Peter Dekoning, Lana Miller and Natalie Newman.

Thank you to Don Morgan from MoE and Lars Reese-Hanson from FLNRORD for a living demonstration of people that obviously love their work and care deeply for the Owen Creek and greater Morice/Bulkley River watersheds.

Thank you to the crew at Eclipse Geomatics for all your help since 2017 and your invaluable curating of important knowledge and technology. Thank you Johanna Pfalz, Lizzy Hoffman and Ekaterina Daviel.

Thank you to Marc Gaboury for making space to discuss his work with Wet’suwet’en First Nation and Mike Smith (LGL Limited) to prescribe/implement fish passage restoration works and a series of other innovative restoration prescriptions within the upper Bulkley River.

We are extremely glad that Jonathan Van Barneveld, Forester - FLNR hunts waterfalls and is very good at it. His input was monstrous for connectivity planning in the watershed. Thank you.

Michael Price is busy enough to produce numerous documents with enormous depth yet finds the time to attend meetings and help answer old questions. Thank you.

We are grateful for Ian Sharpe's input. Ian helps coordinate stewardship programs (Morice Watershed Monitoring Trust) of great importance and authors wonderful documents (including one that inspired this report's acknowledgment section - Upper Bulkley and Morice Water and Salmon Sustainability Views - 2019) yet also finds the time to return phone calls, contribute to conference calls and help answer old questions.

Cindy Verbeek from the Upper Bulkley Streamkeepers has been very giving.  She took time off from running the Buck Creek hatchery and from building the new Watershed Stewardship Centre in Houston to tour us on some key sites in the field, fill us in about important context for Upper Bulkley streams and to vouch for us with the kind and generous local land owner - Roger Groot. Thank you.

Thank you to Matt Sear and Dave Ripmeester from Pacific Inland Resources as well as Jesse Ahtiainen, Kevin Skarda and Vince Ross from Canadian Forest Products Ltd.  You saved us a ton of field time by taking the time for meetings, answering emails and sharing your valuable information.  

Thank you Jeff Anderson from Geomorphic Consulting for helping us see a bigger picture.

Our gratitude to Phil MacDonald from BC Timber Sales, Matt Hawkins from MoTI and Steve Page from FLNRORD for sharing their experience to help devise tools to estimate costs for remedial works.

Thank you to Joe Thorley from Poisson Consulting Ltd.  The probability of better advise is negligible.

The contribution of all the working group members has been wonderful and hopefully some of the information in this report will be helpful towards a healthier future for the watershed and the people it supports. Thank you Maureen Luggi, Jesse Stoeppler, Bill Blackwater, Brian Williams and Elaine Sampson.

Many thanks to John DeGagne and Marc Steynen from SERNbc for their guidance, insight and encouragement for multiple aspects of the project. 

Field work for the project was completed by Allan Irvine, R.P.Bio. and Kyle Prince, P.Biol. Hard work, good times, cold water and open sky.  Misiyh. Ham i yaa. Thank you.

There are many others to which we owe our gratitude and please accept our apologies for leaving people out. It has been a great journey catching up to you all and we are so thankful for everyone willing to help.  Please reach out if we did not include you or others yet since the acknowledgment is well deserved.  

Fish passage is a onederful example of how all things are connected and interdependent.  Long term restoration of aquatic connectivity will demonstrate how the things that stand between will eventually fall once we understand together where and how they divide.

Dzïn scudïlh’iy misiyh. Hami yaa nee loosim.




