

# Introduction {#intro}
```{r}
# New Graph Environment was retained by the Canadian Wildlife Federation and Nupgu Limited Partnership in the fall of 2020 to plan and conduct fish passage and habitat confirmation assessments at road-stream crossings as part of connectivity restoration planning targeting westslope cutthrout trout. Although some planning was conducted for both the Elk River watershed upstream of the Elko Dam near Elko, BC and the Flathead River, on the ground surveys in 2020 focused on the Elk River and tributaries located upstream of the Elko Dam. 
```
The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing habitat [@Bramblett_2002; @swalesRoleOffChannelPonds1989; @diebel_etal2015EffectsRoad].  Culverts can present barriers to fish migration due to low water depth, increased water velocity, turbulence, a vertical drop at the culvert outlet and/or maintenance issues [@slaneyFishHabitatRehabilitation1997; @cote_etal2005Fishpassage]. As road crossing structures are commonly upgraded or removed there are numerous opportunities to restore connectivity by ensuring that fish passage considerations are incorporated into repair, replacement, relocation and deactivation designs. 

<br>

In April of 2020, the Society for Ecosystem Restoration Northern British Columbia (SERNbc) undertook an initiative to plan and conduct fish passage restoration planning activities in the Bulkley River and Morice River watershed groups which are sub-basins of the Skeena River watershed.  The initiative was supported by a grant from the Habitat Conservation Trust Fund that leveraged funds committed in the fall of 2019 from the Provincial Fish Passage Remediation Program and the Canadian Wildlife Federation.  New Graph Environment and Hillcrest Geographics were the project team subcontracted to devise the study plan, submit proposals and complete the work which included information gathering, updating and implementation of open source data analysis tools used to quantify and report on potential habitat gains of fish passage restoration for target species, as well as on the ground fish passage assessments and habitat confirmation assessments.  


<br>

In August of 2020, following a province wide prioritization exercise and a series of workshops, the Canadian Wildlife Federation selected the Bulkley River watershed group as a target watershed for connectivity planning efforts supported by a grant from the British Columbia Salmon Restoration and Innovation Fund.  Recognizing synergies between the two initiatives, select project activities of both initiatives became a collaboration between SERNbc and CWF with extensive input from numerous organizations and individuals connected to the watersheds. Although fish passage restoration planning was conducted for both the Morice River watershed group and the Bulkley River watershed group, on the ground surveys in 2020 focused primarily within Bulkley River tributaries.


<br>

Spearheaded by the Canadian Wildlife Federation, a Fish Passage Working Group consisting of First Nations, non-profits, stakeholder groups and regulators was established for the Bulkley River watershed group in the fall of 2020. At the time of reporting, collaborative decision making processes regarding connectivity issues were underway through monthly meetings with results forthcoming in a watershed connectivity remediation plan. At the time of reporting, the scope of connectivity planning explored by the Working Group included the Bulkley River watershed group and not yet the Morice River and other sub-basins of the Skeena River watershed.

<br>

Although remediation and replacement of stream crossing structures can have benefits to local fish populations, the costs of remedial works can be significant and the impacts of the work often complex to evaluate and quantify.  Additionally, allocation of ecosystem restoration funding towards infrastructure upgrades on transportation right of ways are not always considered ethical from all perspectives.  When funds are finite and invested groups are engaged in fund raising, cost benefits and the ethics of crossing replacements should be explored collaboratively alongside the cost benefits and ethics of  alternative restoration activities (ex. transportation corridor relocation/deactivation, land procurement/covenant, cattle exclusion, riparian restoration, habitat complexing, water conservation, etc.) and research.


