--- 
title: "Elk River Watershed Group Fish Passage Restoration Planning"
author:
 - Prepared for Canadian Wildlife Federation
 - Prepared by Al Irvine, B.Sc., R.P.Bio.
 - New Graph Environment
date: "`r Sys.Date()` DRafT"
toc-title: Table of Contents
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: no
github-repo: rstudio/bookdown-demo
description: "My Description."


---

```{r setup, include = TRUE, echo =FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, dpi=36, out.width = "100%")

##define a picture specific output width you can put in chunk headers - not working
photo_width <- "80%"


# fig.align="center", out.width = "90%",
source('R/packages.R')
source('R/functions.R')
source('R/functions-phase2.R')
source('R/tables.R')
source('R/tables-phase2.R')
source('R/tables-phase1-cost-estimate.R')
source('R/tables-phase2-cost-estimate.R')
source('R/extract-fish.R')
source('R/functions-fish.R')
# options(timeout=180)
##bookdown::gitbook
# lof: true
# lot: true

```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


# Executive Summary {.front-matter .unnumbered}

<br>
