##this script will create a xref for summarizing the bcfishpass info in a table

source('R/0310-tables.R')

##make a tibble to run through knitr::kable then paste as a tribble
colnames_prep <- bind_cols(
  names(bcfishpass_phase2),
  names(bcfishpass_phase2) %>% stringr::str_replace_all('_', ' ') %>% stringr::str_to_title()
) %>%
  purrr::set_names(nm = c('bcfishpass', 'report')) %>%
  mutate(id_join = NA_integer_,
         id_side = NA_integer_)


xref_bcfishpass_names <- tibble::tribble(
                                                                          ~bcfishpass,                                                    ~report, ~id_join, ~id_side,
                                                            "aggregated_crossings_id",                                  "Aggregated Crossings Id",       NA,       NA,
                                                                 "stream_crossing_id",                                                 "PSCIS ID",       NA,       NA,
                                                                             "dam_id",                                                   "Dam Id",       NA,       NA,
                                                               "modelled_crossing_id",                                     "Modelled Crossing Id",       NA,       NA,
                                                                    "crossing_source",                                          "Crossing Source",       NA,       NA,
                                                                       "pscis_status",                                             "Pscis Status",       NA,       NA,
                                                                 "crossing_type_code",                                       "Crossing Type Code",       NA,       NA,
                                                              "crossing_subtype_code",                                    "Crossing Subtype Code",       NA,       NA,
                                                      "modelled_crossing_type_source",                            "Modelled Crossing Type Source",       NA,       NA,
                                                                     "barrier_status",                                           "Barrier Status",       NA,       NA,
                                                                    "pscis_road_name",                                          "Pscis Road Name",       NA,       NA,
                                                   "transport_line_structured_name_1",                         "Transport Line Structured Name 1",       NA,       NA,
                                                    "transport_line_type_description",                          "Transport Line Type Description",       NA,       NA,
                                                 "transport_line_surface_description",                       "Transport Line Surface Description",       NA,       NA,
                                                                "ften_forest_file_id",                                      "Ften Forest File Id",       NA,       NA,
                                                         "ften_file_type_description",                               "Ften File Type Description",       NA,       NA,
                                                                 "ften_client_number",                                       "Ften Client Number",       NA,       NA,
                                                                   "ften_client_name",                                         "Ften Client Name",       NA,       NA,
                                                        "ften_life_cycle_status_code",                              "Ften Life Cycle Status Code",       NA,       NA,
                                                                    "rail_track_name",                                          "Rail Track Name",       NA,       NA,
                                                                    "rail_owner_name",                                          "Rail Owner Name",       NA,       NA,
                                                         "rail_operator_english_name",                               "Rail Operator English Name",       NA,       NA,
                                                                      "ogc_proponent",                                            "Ogc Proponent",       NA,       NA,
                                                                           "dam_name",                                                 "Dam Name",       NA,       NA,
                                                                          "dam_owner",                                                "Dam Owner",       NA,       NA,
                                                                  "wcrp_barrier_type",                                        "Wcrp Barrier Type",       NA,       NA,
                                                                           "utm_zone",                                                 "UTM Zone",       NA,       NA,
                                                                        "utm_easting",                                              "UTM Easting",       NA,       NA,
                                                                       "utm_northing",                                             "UTM Northing",       NA,       NA,
                                                                  "linear_feature_id",                                        "Linear Feature Id",       NA,       NA,
                                                                      "blue_line_key",                                            "Blue Line Key",       NA,       NA,
                                                           "downstream_route_measure",                                 "Downstream Route Measure",       NA,       NA,
                                                                       "wscode_ltree",                                             "Wscode Ltree",       NA,       NA,
                                                                    "localcode_ltree",                                          "Localcode Ltree",       NA,       NA,
                                                               "watershed_group_code",                                     "Watershed Group Code",       NA,       NA,
                                                                    "dnstr_crossings",                                          "Dnstr Crossings",       NA,       NA,
                                                       "dnstr_barriers_anthropogenic",                             "Dnstr Barriers Anthropogenic",       NA,       NA,
                                                                       "stream_order",                                             "Stream Order",       NA,       NA,
                                                                   "stream_magnitude",                                         "Stream Magnitude",       NA,       NA,
                                                                           "gradient",                                                 "Gradient",       NA,       NA,
                                                         "accessibility_model_salmon",                               "Accessibility Model Salmon",       NA,       NA,
                                                      "accessibility_model_steelhead",                            "Accessibility Model Steelhead",       NA,       NA,
                                                            "accessibility_model_wct",                                  "Accessibility Model Wct",       NA,       NA,
                                                                  "observedspp_dnstr",                                        "Observedspp Dnstr",       NA,       NA,
                                                                  "observedspp_upstr",                                        "Observedspp Upstr",       NA,       NA,
                                                                 "watershed_upstr_ha",                                      "Watershed Area (ha)",       NA,       NA,
                                                                   "total_network_km",                                         "Total Network Km",       NA,       NA,
                                                                    "total_stream_km",                                          "Total Stream Km",       NA,       NA,
                                                             "total_lakereservoir_ha",                                   "Total Lakereservoir Ha",       NA,       NA,
                                                                   "total_wetland_ha",                                         "Total Wetland Ha",       NA,       NA,
                                                  "total_slopeclass03_waterbodies_km",                        "Total Slopeclass03 Waterbodies Km",       NA,       NA,
                                                              "total_slopeclass03_km",                                    "Total Slopeclass03 Km",       NA,       NA,
                                                              "total_slopeclass05_km",                                    "Total Slopeclass05 Km",       NA,       NA,
                                                              "total_slopeclass08_km",                                    "Total Slopeclass08 Km",       NA,       NA,
                                                              "total_slopeclass15_km",                                    "Total Slopeclass15 Km",       NA,       NA,
                                                              "total_slopeclass22_km",                                    "Total Slopeclass22 Km",       NA,       NA,
                                                              "total_slopeclass30_km",                                    "Total Slopeclass30 Km",       NA,       NA,
                                                "total_belowupstrbarriers_network_km",                      "Total Belowupstrbarriers Network Km",       NA,       NA,
                                                 "total_belowupstrbarriers_stream_km",                       "Total Belowupstrbarriers Stream Km",       NA,       NA,
                                          "total_belowupstrbarriers_lakereservoir_ha",                "Total Belowupstrbarriers Lakereservoir Ha",       NA,       NA,
                                                "total_belowupstrbarriers_wetland_ha",                      "Total Belowupstrbarriers Wetland Ha",       NA,       NA,
                               "total_belowupstrbarriers_slopeclass03_waterbodies_km",     "Total Belowupstrbarriers Slopeclass03 Waterbodies Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass03_km",                 "Total Belowupstrbarriers Slopeclass03 Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass05_km",                 "Total Belowupstrbarriers Slopeclass05 Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass08_km",                 "Total Belowupstrbarriers Slopeclass08 Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass15_km",                 "Total Belowupstrbarriers Slopeclass15 Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass22_km",                 "Total Belowupstrbarriers Slopeclass22 Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass30_km",                 "Total Belowupstrbarriers Slopeclass30 Km",       NA,       NA,
                                                                  "salmon_network_km",                                        "Salmon Network Km",       NA,       NA,
                                                                   "salmon_stream_km",                                         "Salmon Stream Km",       NA,       NA,
                                                            "salmon_lakereservoir_ha",                                  "Salmon Lakereservoir Ha",       NA,       NA,
                                                                  "salmon_wetland_ha",                                        "Salmon Wetland Ha",       NA,       NA,
                                                 "salmon_slopeclass03_waterbodies_km",                       "Salmon Slopeclass03 Waterbodies Km",       NA,       NA,
                                                             "salmon_slopeclass03_km",                                   "Salmon Slopeclass03 Km",       NA,       NA,
                                                             "salmon_slopeclass05_km",                                   "Salmon Slopeclass05 Km",       NA,       NA,
                                                             "salmon_slopeclass08_km",                                   "Salmon Slopeclass08 Km",       NA,       NA,
                                                             "salmon_slopeclass15_km",                                   "Salmon Slopeclass15 Km",       NA,       NA,
                                                             "salmon_slopeclass22_km",                                   "Salmon Slopeclass22 Km",       NA,       NA,
                                                             "salmon_slopeclass30_km",                                   "Salmon Slopeclass30 Km",       NA,       NA,
                                               "salmon_belowupstrbarriers_network_km",                     "Salmon Belowupstrbarriers Network Km",       NA,       NA,
                                                "salmon_belowupstrbarriers_stream_km",                      "Salmon Belowupstrbarriers Stream Km",       NA,       NA,
                                         "salmon_belowupstrbarriers_lakereservoir_ha",               "Salmon Belowupstrbarriers Lakereservoir Ha",       NA,       NA,
                                               "salmon_belowupstrbarriers_wetland_ha",                     "Salmon Belowupstrbarriers Wetland Ha",       NA,       NA,
                              "salmon_belowupstrbarriers_slopeclass03_waterbodies_km",    "Salmon Belowupstrbarriers Slopeclass03 Waterbodies Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass03_km",                "Salmon Belowupstrbarriers Slopeclass03 Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass05_km",                "Salmon Belowupstrbarriers Slopeclass05 Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass08_km",                "Salmon Belowupstrbarriers Slopeclass08 Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass15_km",                "Salmon Belowupstrbarriers Slopeclass15 Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass22_km",                "Salmon Belowupstrbarriers Slopeclass22 Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass30_km",                "Salmon Belowupstrbarriers Slopeclass30 Km",       NA,       NA,
                                                               "steelhead_network_km",                                     "Steelhead Network Km",       NA,       NA,
                                                                "steelhead_stream_km",                                      "Steelhead Stream Km",       NA,       NA,
                                                         "steelhead_lakereservoir_ha",                               "Steelhead Lakereservoir Ha",       NA,       NA,
                                                               "steelhead_wetland_ha",                                     "Steelhead Wetland Ha",       NA,       NA,
                                              "steelhead_slopeclass03_waterbodies_km",                    "Steelhead Slopeclass03 Waterbodies Km",       NA,       NA,
                                                          "steelhead_slopeclass03_km",                                "Steelhead Slopeclass03 Km",       NA,       NA,
                                                          "steelhead_slopeclass05_km",                                "Steelhead Slopeclass05 Km",       NA,       NA,
                                                          "steelhead_slopeclass08_km",                                "Steelhead Slopeclass08 Km",       NA,       NA,
                                                          "steelhead_slopeclass15_km",                                "Steelhead Slopeclass15 Km",       NA,       NA,
                                                          "steelhead_slopeclass22_km",                                "Steelhead Slopeclass22 Km",       NA,       NA,
                                                          "steelhead_slopeclass30_km",                                "Steelhead Slopeclass30 Km",       NA,       NA,
                                            "steelhead_belowupstrbarriers_network_km",                  "Steelhead Belowupstrbarriers Network Km",       NA,       NA,
                                             "steelhead_belowupstrbarriers_stream_km",                   "Steelhead Belowupstrbarriers Stream Km",       NA,       NA,
                                      "steelhead_belowupstrbarriers_lakereservoir_ha",            "Steelhead Belowupstrbarriers Lakereservoir Ha",       NA,       NA,
                                            "steelhead_belowupstrbarriers_wetland_ha",                  "Steelhead Belowupstrbarriers Wetland Ha",       NA,       NA,
                           "steelhead_belowupstrbarriers_slopeclass03_waterbodies_km", "Steelhead Belowupstrbarriers Slopeclass03 Waterbodies Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass03_km",             "Steelhead Belowupstrbarriers Slopeclass03 Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass05_km",             "Steelhead Belowupstrbarriers Slopeclass05 Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass08_km",             "Steelhead Belowupstrbarriers Slopeclass08 Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass15_km",             "Steelhead Belowupstrbarriers Slopeclass15 Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass22_km",             "Steelhead Belowupstrbarriers Slopeclass22 Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass30_km",             "Steelhead Belowupstrbarriers Slopeclass30 Km",       NA,       NA,
                                                                     "wct_network_km",                                           "Wct Network Km",       NA,       NA,
                                                                      "wct_stream_km",                                            "Wct Stream Km",       NA,       NA,
                                                               "wct_lakereservoir_ha",                                     "Wct Lakereservoir Ha",       NA,       NA,
                                                                     "wct_wetland_ha",                                           "Wct Wetland Ha",       NA,       NA,
                                                    "wct_slopeclass03_waterbodies_km",                          "Wct Slopeclass03 Waterbodies Km",       NA,       NA,
                                                                "wct_slopeclass03_km",                                      "Wct Slopeclass03 Km",       NA,       NA,
                                                                "wct_slopeclass05_km",                                      "Wct Slopeclass05 Km",       NA,       NA,
                                                                "wct_slopeclass08_km",                                      "Wct Slopeclass08 Km",       NA,       NA,
                                                                "wct_slopeclass15_km",                                      "Wct Slopeclass15 Km",       NA,       NA,
                                                                "wct_slopeclass22_km",                                      "Wct Slopeclass22 Km",       NA,       NA,
                                                                "wct_slopeclass30_km",                                      "Wct Slopeclass30 Km",       NA,       NA,
                                                  "wct_belowupstrbarriers_network_km",                        "Wct Belowupstrbarriers Network Km",       NA,       NA,
                                                   "wct_belowupstrbarriers_stream_km",                         "Wct Belowupstrbarriers Stream Km",       NA,       NA,
                                            "wct_belowupstrbarriers_lakereservoir_ha",                  "Wct Belowupstrbarriers Lakereservoir Ha",       NA,       NA,
                                                  "wct_belowupstrbarriers_wetland_ha",                        "Wct Belowupstrbarriers Wetland Ha",       NA,       NA,
                                 "wct_belowupstrbarriers_slopeclass03_waterbodies_km",       "Wct Belowupstrbarriers Slopeclass03 Waterbodies Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass03_km",                   "Wct Belowupstrbarriers Slopeclass03 Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass05_km",                   "Wct Belowupstrbarriers Slopeclass05 Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass08_km",                   "Wct Belowupstrbarriers Slopeclass08 Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass15_km",                   "Wct Belowupstrbarriers Slopeclass15 Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass22_km",                   "Wct Belowupstrbarriers Slopeclass22 Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass30_km",                   "Wct Belowupstrbarriers Slopeclass30 Km",       NA,       NA,
                                                                     "ch_spawning_km",                                           "Ch Spawning Km",       NA,       NA,
                                                                      "ch_rearing_km",                                            "Ch Rearing Km",       NA,       NA,
                                                  "ch_spawning_belowupstrbarriers_km",                           "CH Spawning Below Barriers (km)",       NA,       NA,
                                                   "ch_rearing_belowupstrbarriers_km",                         "CH Rearing Belowupstrbarriers (km)",       NA,       NA,
                                                                     "co_spawning_km",                                           "Co Spawning (km)",       NA,       NA,
                                                                      "co_rearing_km",                                            "Co Rearing (km)",       NA,       NA,
                                                  "co_spawning_belowupstrbarriers_km",                        "Co Spawning Belowupstrbarriers (km)",       NA,       NA,
                                                   "co_rearing_belowupstrbarriers_km",                         "Co Rearing Belowupstrbarriers (km)",       NA,       NA,
                                                                     "sk_spawning_km",                                           "Sk Spawning (km)",       NA,       NA,
                                                                      "sk_rearing_km",                                            "Sk Rearing (km)",       NA,       NA,
                                                  "sk_spawning_belowupstrbarriers_km",                        "Sk Spawning Belowupstrbarriers (km)",       NA,       NA,
                                                   "sk_rearing_belowupstrbarriers_km",                         "Sk Rearing Belowupstrbarriers (km)",       NA,       NA,
                                                                     "st_spawning_km",                                           "St Spawning (km)",       NA,       NA,
                                                                      "st_rearing_km",                                            "St Rearing (km)",       NA,       NA,
                                                  "st_spawning_belowupstrbarriers_km",                        "St Spawning Belowupstrbarriers (km)",       NA,       NA,
                                                   "st_rearing_belowupstrbarriers_km",                         "St Rearing Belowupstrbarriers (km)",       NA,       NA,
                                                                    "all_spawning_km",                                          "All Spawning (km)",       NA,       NA,
                                                 "all_spawning_belowupstrbarriers_km",                       "All Spawning Belowupstrbarriers (km)",       NA,       NA,
                                                                     "all_rearing_km",                                           "All Rearing (km)",       NA,       NA,
                                                  "all_rearing_belowupstrbarriers_km",                        "All Rearing Belowupstrbarriers (km)",       NA,       NA,
                                                             "all_spawningrearing_km",                                   "All Spawningrearing (km)",       NA,       NA,
                                          "all_spawningrearing_belowupstrbarriers_km",                "All Spawningrearing Belowupstrbarriers (km)",       NA,       NA,
                                                                   "dbm_mof_50k_grid",                                             "Mapsheet (50k)",       NA,       NA,
                                                                            "easting",                                                  "Easting",       NA,       NA,
                                                                           "northing",                                                 "Northing",       NA,       NA
                           )

