##this script will create a xref for summarizing the bcfishpass info in a table

source('R/0310-tables.R')

##make a tibble to run through knitr::kable then paste as a tribble
colnames_prep <- bind_cols(
  names(bcfishpass_phase2),
  names(bcfishpass_phase2) %>% stringr::str_replace_all('_', ' ') %>% stringr::str_to_title()
) %>%
  purrr::set_names(nm = c('bcfishpass', 'report')) %>%
  mutate(id_join = NA_integer_,
         id_side = NA_integer_)


xref_bcfishpass_names <- tibble::tribble(
                                                                          ~bcfishpass,                                                    ~report, ~id_join, ~id_side,
                                                            "aggregated_crossings_id",                                  "Aggregated Crossings Id",       NA,       NA,
                                                                 "stream_crossing_id",                                                 "PSCIS ID",       NA,       NA,
                                                                             "dam_id",                                                   "Dam Id",       NA,       NA,
                                                      "misc_barrier_anthropogenic_id",                            "Misc Barrier Anthropogenic Id",       NA,       NA,
                                                               "modelled_crossing_id",                                     "Modelled Crossing Id",       NA,       NA,
                                                                    "crossing_source",                                          "Crossing Source",       NA,       NA,
                                                                       "pscis_status",                                             "Pscis Status",       NA,       NA,
                                                                 "crossing_type_code",                                       "Crossing Type Code",       NA,       NA,
                                                              "crossing_subtype_code",                                    "Crossing Subtype Code",       NA,       NA,
                                                      "modelled_crossing_type_source",                            "Modelled Crossing Type Source",       NA,       NA,
                                                                     "barrier_status",                                           "Barrier Status",       NA,       NA,
                                                                    "pscis_road_name",                                          "Pscis Road Name",       NA,       NA,
                                                   "transport_line_structured_name_1",                         "Transport Line Structured Name 1",       NA,       NA,
                                                    "transport_line_type_description",                          "Transport Line Type Description",       NA,       NA,
                                                 "transport_line_surface_description",                       "Transport Line Surface Description",       NA,       NA,
                                                                "ften_forest_file_id",                                      "Ften Forest File Id",       NA,       NA,
                                                         "ften_file_type_description",                               "Ften File Type Description",       NA,       NA,
                                                                 "ften_client_number",                                       "Ften Client Number",       NA,       NA,
                                                                   "ften_client_name",                                         "Ften Client Name",       NA,       NA,
                                                        "ften_life_cycle_status_code",                              "Ften Life Cycle Status Code",       NA,       NA,
                                                                    "rail_track_name",                                          "Rail Track Name",       NA,       NA,
                                                                    "rail_owner_name",                                          "Rail Owner Name",       NA,       NA,
                                                         "rail_operator_english_name",                               "Rail Operator English Name",       NA,       NA,
                                                                      "ogc_proponent",                                            "Ogc Proponent",       NA,       NA,
                                                                           "dam_name",                                                 "Dam Name",       NA,       NA,
                                                                          "dam_owner",                                                "Dam Owner",       NA,       NA,
                                                                  "wcrp_barrier_type",                                        "Wcrp Barrier Type",       NA,       NA,
                                                                           "utm_zone",                                                 "UTM Zone",       NA,       NA,
                                                                        "utm_easting",                                              "UTM Easting",       NA,       NA,
                                                                       "utm_northing",                                             "UTM Northing",       NA,       NA,
                                                                  "linear_feature_id",                                        "Linear Feature Id",       NA,       NA,
                                                                      "blue_line_key",                                            "Blue Line Key",       NA,       NA,
                                                           "downstream_route_measure",                                 "Downstream Route Measure",       NA,       NA,
                                                                       "wscode_ltree",                                             "Wscode Ltree",       NA,       NA,
                                                                    "localcode_ltree",                                          "Localcode Ltree",       NA,       NA,
                                                               "watershed_group_code",                                     "Watershed Group Code",       NA,       NA,
                                                                    "dnstr_crossings",                                          "Dnstr Crossings",       NA,       NA,
                                                       "dnstr_barriers_anthropogenic",                             "Dnstr Barriers Anthropogenic",       NA,       NA,
                                                                       "stream_order",                                             "Stream Order",       NA,       NA,
                                                                   "stream_magnitude",                                         "Stream Magnitude",       NA,       NA,
                                                                           "gradient",                                                 "Gradient",       NA,       NA,
                                                         "accessibility_model_salmon",                               "Accessibility Model Salmon",       NA,       NA,
                                                      "accessibility_model_steelhead",                            "Accessibility Model Steelhead",       NA,       NA,
                                                            "accessibility_model_wct",                                  "Accessibility Model Wct",       NA,       NA,
                                                                  "observedspp_dnstr",                                        "Observedspp Dnstr",       NA,       NA,
                                                                  "observedspp_upstr",                                        "Observedspp Upstr",       NA,       NA,
                                                                 "watershed_upstr_ha",                                      "Watershed Area (ha)",       NA,       NA,
                                                                   "total_network_km",                                         "Total Network Km",      NA,       NA,
                                                                    "total_stream_km",                                          "Total Stream Km",       NA,       NA,
                                                             "total_lakereservoir_ha",                                   "Total Lakereservoir Ha",      NA,       NA,
                                                                   "total_wetland_ha",                                         "Total Wetland Ha",      NA,       NA,
                                                  "total_slopeclass03_waterbodies_km",                        "Total Slopeclass03 Waterbodies Km",       NA,       NA,
                                                              "total_slopeclass03_km",                                    "Total Slopeclass03 Km",       NA,       NA,
                                                              "total_slopeclass05_km",                                    "Total Slopeclass05 Km",       NA,       NA,
                                                              "total_slopeclass08_km",                                    "Total Slopeclass08 Km",       NA,       NA,
                                                              "total_slopeclass15_km",                                    "Total Slopeclass15 Km",       NA,       NA,
                                                              "total_slopeclass22_km",                                    "Total Slopeclass22 Km",       NA,       NA,
                                                              "total_slopeclass30_km",                                    "Total Slopeclass30 Km",       NA,       NA,
                                                "total_belowupstrbarriers_network_km",                      "Total Below Barriers Network Km",      NA,       NA,
                                                 "total_belowupstrbarriers_stream_km",                       "Total Below Barriers Stream Km",       NA,       NA,
                                          "total_belowupstrbarriers_lakereservoir_ha",                "Total Below Barriers Lakereservoir Ha",      NA,       NA,
                                                "total_belowupstrbarriers_wetland_ha",                      "Total Below Barriers Wetland Ha",      NA,       NA,
                               "total_belowupstrbarriers_slopeclass03_waterbodies_km",     "Total Below Barriers Slopeclass03 Waterbodies Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass03_km",                 "Total Below Barriers Slopeclass03 Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass05_km",                 "Total Below Barriers Slopeclass05 Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass08_km",                 "Total Below Barriers Slopeclass08 Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass15_km",                 "Total Below Barriers Slopeclass15 Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass22_km",                 "Total Below Barriers Slopeclass22 Km",       NA,       NA,
                                           "total_belowupstrbarriers_slopeclass30_km",                 "Total Below Barriers Slopeclass30 Km",       NA,       NA,
                                                                  "salmon_network_km",                                        "Salmon Network Km",      70L,       1L,
                                                                   "salmon_stream_km",                                         "Salmon Stream Km",       NA,       NA,
                                                            "salmon_lakereservoir_ha",                                  "Salmon Lakereservoir Ha",      80L,       1L,
                                                                  "salmon_wetland_ha",                                        "Salmon Wetland Ha",      90L,       1L,
                                                 "salmon_slopeclass03_waterbodies_km",                       "Salmon Slopeclass03 Waterbodies Km",       NA,       NA,
                                                             "salmon_slopeclass03_km",                                   "Salmon Slopeclass03 Km",       NA,       NA,
                                                             "salmon_slopeclass05_km",                                   "Salmon Slopeclass05 Km",       NA,       NA,
                                                             "salmon_slopeclass08_km",                                   "Salmon Slopeclass08 Km",       NA,       NA,
                                                             "salmon_slopeclass15_km",                                   "Salmon Slopeclass15 Km",       NA,       NA,
                                                             "salmon_slopeclass22_km",                                   "Salmon Slopeclass22 Km",       NA,       NA,
                                                             "salmon_slopeclass30_km",                                   "Salmon Slopeclass30 Km",       NA,       NA,
                                               "salmon_belowupstrbarriers_network_km",                     "Salmon Below Barriers Network Km",      70L,       2L,
                                                "salmon_belowupstrbarriers_stream_km",                      "Salmon Below Barriers Stream Km",       NA,       NA,
                                         "salmon_belowupstrbarriers_lakereservoir_ha",               "Salmon Below Barriers Lakereservoir Ha",      80L,       2L,
                                               "salmon_belowupstrbarriers_wetland_ha",                     "Salmon Below Barriers Wetland Ha",      90L,       2L,
                              "salmon_belowupstrbarriers_slopeclass03_waterbodies_km",    "Salmon Below Barriers Slopeclass03 Waterbodies Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass03_km",                "Salmon Below Barriers Slopeclass03 Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass05_km",                "Salmon Below Barriers Slopeclass05 Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass08_km",                "Salmon Below Barriers Slopeclass08 Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass15_km",                "Salmon Below Barriers Slopeclass15 Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass22_km",                "Salmon Below Barriers Slopeclass22 Km",       NA,       NA,
                                          "salmon_belowupstrbarriers_slopeclass30_km",                "Salmon Below Barriers Slopeclass30 Km",       NA,       NA,
                                                               "steelhead_network_km",                                     "Steelhead Network Km",     100L,       1L,
                                                                "steelhead_stream_km",                                      "Steelhead Stream Km",       NA,       NA,
                                                         "steelhead_lakereservoir_ha",                               "Steelhead Lakereservoir Ha",     102L,       1L,
                                                               "steelhead_wetland_ha",                                     "Steelhead Wetland Ha",     103L,       1L,
                                              "steelhead_slopeclass03_waterbodies_km",                    "Steelhead Slopeclass03 Waterbodies Km",       NA,       NA,
                                                          "steelhead_slopeclass03_km",                                "Steelhead Slopeclass03 Km",       NA,       NA,
                                                          "steelhead_slopeclass05_km",                                "Steelhead Slopeclass05 Km",       NA,       NA,
                                                          "steelhead_slopeclass08_km",                                "Steelhead Slopeclass08 Km",       NA,       NA,
                                                          "steelhead_slopeclass15_km",                                "Steelhead Slopeclass15 Km",       NA,       NA,
                                                          "steelhead_slopeclass22_km",                                "Steelhead Slopeclass22 Km",       NA,       NA,
                                                          "steelhead_slopeclass30_km",                                "Steelhead Slopeclass30 Km",       NA,       NA,
                                            "steelhead_belowupstrbarriers_network_km",                  "Steelhead Below Barriers Network Km",     100L,       2L,
                                             "steelhead_belowupstrbarriers_stream_km",                   "Steelhead Below Barriers Stream Km",       NA,       NA,
                                      "steelhead_belowupstrbarriers_lakereservoir_ha",            "Steelhead Below Barriers Lakereservoir Ha",     102L,       2L,
                                            "steelhead_belowupstrbarriers_wetland_ha",                  "Steelhead Below Barriers Wetland Ha",     103L,       2L,
                           "steelhead_belowupstrbarriers_slopeclass03_waterbodies_km", "Steelhead Below Barriers Slopeclass03 Waterbodies Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass03_km",             "Steelhead Below Barriers Slopeclass03 Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass05_km",             "Steelhead Below Barriers Slopeclass05 Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass08_km",             "Steelhead Below Barriers Slopeclass08 Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass15_km",             "Steelhead Below Barriers Slopeclass15 Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass22_km",             "Steelhead Below Barriers Slopeclass22 Km",       NA,       NA,
                                       "steelhead_belowupstrbarriers_slopeclass30_km",             "Steelhead Below Barriers Slopeclass30 Km",       NA,       NA,
                                                                     "wct_network_km",                                           "Wct Network Km",       NA,       NA,
                                                                      "wct_stream_km",                                            "Wct Stream Km",       NA,       NA,
                                                               "wct_lakereservoir_ha",                                     "Wct Lakereservoir Ha",       NA,       NA,
                                                                     "wct_wetland_ha",                                           "Wct Wetland Ha",       NA,       NA,
                                                    "wct_slopeclass03_waterbodies_km",                          "Wct Slopeclass03 Waterbodies Km",       NA,       NA,
                                                                "wct_slopeclass03_km",                                      "Wct Slopeclass03 Km",       NA,       NA,
                                                                "wct_slopeclass05_km",                                      "Wct Slopeclass05 Km",       NA,       NA,
                                                                "wct_slopeclass08_km",                                      "Wct Slopeclass08 Km",       NA,       NA,
                                                                "wct_slopeclass15_km",                                      "Wct Slopeclass15 Km",       NA,       NA,
                                                                "wct_slopeclass22_km",                                      "Wct Slopeclass22 Km",       NA,       NA,
                                                                "wct_slopeclass30_km",                                      "Wct Slopeclass30 Km",       NA,       NA,
                                                  "wct_belowupstrbarriers_network_km",                        "Wct Below Barriers Network Km",       NA,       NA,
                                                   "wct_belowupstrbarriers_stream_km",                         "Wct Below Barriers Stream Km",       NA,       NA,
                                            "wct_belowupstrbarriers_lakereservoir_ha",                  "Wct Below Barriers Lakereservoir Ha",       NA,       NA,
                                                  "wct_belowupstrbarriers_wetland_ha",                        "Wct Below Barriers Wetland Ha",       NA,       NA,
                                 "wct_belowupstrbarriers_slopeclass03_waterbodies_km",       "Wct Below Barriers Slopeclass03 Waterbodies Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass03_km",                   "Wct Below Barriers Slopeclass03 Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass05_km",                   "Wct Below Barriers Slopeclass05 Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass08_km",                   "Wct Below Barriers Slopeclass08 Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass15_km",                   "Wct Below Barriers Slopeclass15 Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass22_km",                   "Wct Below Barriers Slopeclass22 Km",       NA,       NA,
                                             "wct_belowupstrbarriers_slopeclass30_km",                   "Wct Below Barriers Slopeclass30 Km",       NA,       NA,
                                                                     "ch_spawning_km",                                           "CH Spawning Km",     110L,       1L,
                                                                      "ch_rearing_km",                                            "CH Rearing Km",     120L,       1L,
                                                  "ch_spawning_belowupstrbarriers_km",                          "CH Spawning Below Barriers (km)",     110L,       2L,
                                                   "ch_rearing_belowupstrbarriers_km",                       "CH Rearing Below Barriers (km)",     120L,       2L,
                                                                     "co_spawning_km",                                         "CO Spawning (km)",     130L,       1L,
                                                                      "co_rearing_km",                                          "CO Rearing (km)",     140L,       1L,
                                                  "co_spawning_belowupstrbarriers_km",                      "CO Spawning Below Barriers (km)",     130L,       2L,
                                                   "co_rearing_belowupstrbarriers_km",                       "CO Rearing Below Barriers (km)",     140L,       2L,
                                                                     "sk_spawning_km",                                         "SK Spawning (km)",     150L,       1L,
                                                                      "sk_rearing_km",                                          "SK Rearing (km)",     160L,       1L,
                                                  "sk_spawning_belowupstrbarriers_km",                      "SK Spawning Below Barriers (km)",     150L,       2L,
                                                   "sk_rearing_belowupstrbarriers_km",                       "SK Rearing Below Barriers (km)",     160L,       2L,
                                                                     "st_spawning_km",                                         "ST Spawning (km)",     170L,       1L,
                                                                      "st_rearing_km",                                          "ST Rearing (km)",     180L,       1L,
                                                  "st_spawning_belowupstrbarriers_km",                      "ST Spawning Below Barriers (km)",     170L,       2L,
                                                   "st_rearing_belowupstrbarriers_km",                       "ST Rearing Below Barriers (km)",     180L,       2L,
                                                                    "all_spawning_km",                                        "All Spawning (km)",     190L,       1L,
                                                 "all_spawning_belowupstrbarriers_km",                     "All Spawning Below Barriers (km)",     190L,       2L,
                                                                     "all_rearing_km",                                         "All Rearing (km)",     200L,       1L,
                                                  "all_rearing_belowupstrbarriers_km",                      "All Rearing Below Barriers (km)",     200L,       2L,
                                                             "all_spawningrearing_km",                                 "All Spawningrearing (km)",     210L,       1L,
                                          "all_spawningrearing_belowupstrbarriers_km",              "All Spawningrearing Below Barriers (km)",     210L,       2L,
                                                                   "dbm_mof_50k_grid",                                           "Mapsheet (50k)",      NA,        NA
                                                                   # "channel_width_modelled",                         "Channel Width Modelled (m)",      35L,       1L,
                                                                   # "discharge_modelled",                              "Discharge Modelled (m3/s)",      35L,       2L
)






